// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBuBaYn_RxibS-dAaoPhJBv30MDoLe-oY',
    appId: '1:780890462285:web:495e353d3c64ca85c66404',
    messagingSenderId: '780890462285',
    projectId: 'flutops',
    authDomain: 'flutops.firebaseapp.com',
    storageBucket: 'flutops.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvnkQXHbQCgqk59FKsWb7F83cvbW_Csxo',
    appId: '1:780890462285:android:e102db8030a94df7c66404',
    messagingSenderId: '780890462285',
    projectId: 'flutops',
    storageBucket: 'flutops.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE82KeJBwa92fXQvqgWPYJObRV3WUmIeM',
    appId: '1:780890462285:ios:b1e9c438f649a92ec66404',
    messagingSenderId: '780890462285',
    projectId: 'flutops',
    storageBucket: 'flutops.firebasestorage.app',
    iosBundleId: 'com.example.myDevops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE82KeJBwa92fXQvqgWPYJObRV3WUmIeM',
    appId: '1:780890462285:ios:b1e9c438f649a92ec66404',
    messagingSenderId: '780890462285',
    projectId: 'flutops',
    storageBucket: 'flutops.firebasestorage.app',
    iosBundleId: 'com.example.myDevops',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBuBaYn_RxibS-dAaoPhJBv30MDoLe-oY',
    appId: '1:780890462285:web:49f5097062974a46c66404',
    messagingSenderId: '780890462285',
    projectId: 'flutops',
    authDomain: 'flutops.firebaseapp.com',
    storageBucket: 'flutops.firebasestorage.app',
  );
}
